### ISSUE TITLE
Roadmap to collab on this project

### ISSUE THREAD

**Issue by stefanjudis** [contentful-userland/gatsby-contentful-starter#1]
As already discussed in 

https://github.com/contentful-userland/project-requests/issues/1#issuecomment-360355298

the following features should go in. :) 

- languages/locales
- gatsby offline/manifest and everything to get pwa
- some client side features
- page transitions
- some elaborated content
- gatsby-image for everything
- some very lightweight css framework? also purify-css is available
- preview api

Afaik [the default starter](https://github.com/gatsbyjs/gatsby-starter-default) is the way to kick things off or? 

cc. @axe312ger @mattbag @aderaaij

**Comment by bennias** [comment]
@stefanjudis Sounds great! What do you think about https://picturepan2.github.io/spectre/ ?

**Comment by stefanjudis** [comment]
Yeah, works for me. Usually, I don't have strong feelings on a css framework. :)

**Comment by axe312ger** [comment]
About spectre: Looks neat, I'd just go for css grid for layouting instead of spamming `col-X` into the markup :)

**Comment by mattbag** [comment]
Yes to all, the starter is as good as barebones, so all good on spectre too.
Should we pick a theme/purpose for the theme?

**Comment by stefanjudis** [comment]
I'd go with a classic blog/portfolio theme. That's not fancy but usable. :)

**Comment by axe312ger** [comment]
Just want to throw in https://github.com/contentful/content-models/ since we manage content-models there and it might be an option to use one of these or add another one for this starter-kit

**Comment by stefanjudis** [comment]
Okay so what about following steps to do: 

- [ ] set up default starter
- [ ] figure out how/when to set up content in contentful
- [ ] connect starter with the created account

When these are set we can tackle the rest: 
- [ ] languages/locales
- [ ] gatsby offline/manifest and everything to get pwa
- [ ] page transitions
- [ ] some elaborated content
- [ ] gatsby-image for everything (Images API)
- [ ] preview dev environment

Everybody cool with that? 

Also FYI I think I'll enable https://probot.github.io/apps/invite-contributors/ for this org, so when one a PR gets merged the contributor becomes part of the org. 🎉

**Comment by stefanjudis** [comment]
Hello everybody... I just pushed the initial version of the starter! I have to say Gatsby is quite nice.

You can have a look at the setup after a few minutes here 👇 
https://contentful-userland.github.io/gatsby-contentful-starter/

If anyone is still up for giving it a spin and some collaboration I created a few issues and added a roadmap. :)

https://github.com/contentful-userland/gatsby-contentful-starter#roadmap

Closing for now here. If anyone has some feedback I'd love to hear it.

**Comment by mattbag** [comment]
Sorry I just got a nice idea, I think. We should have a palette or theme config file to allow people to quickly style the starter. I'll try to make something, just need to know what css style to use (and time)

**Comment by stefanjudis** [comment]
@mattbag 

That sounds awesome! 😲
Could you make an issue about that so that we can bounce ideas? 😊
